import { defineTexts, text, textWith, type TextEntry } from "./helpers";
import { grade1Texts, type TextKey } from "./grade1";

export const grade5Texts = defineTexts<Record<TextKey, TextEntry>>({
  ...grade1Texts,
  navSummary: text("サマリー"),
  navAll: text("一覧"),
  navAssetsSettings: text("資産設定"),
  navCategoriesSettings: text("カテゴリ設定"),
  dashboardTitle: text("サマリー"),
  dashboardSubtitle: text("いまの状況を確認"),
  dashboardAllLabel: text("全体"),
  dashboardInitialBalance: textWith(({ amount }) => `初期残高 ${amount ?? ""}`.trim()),
  dashboardMonthIncome: text("今月の収入"),
  dashboardMonthExpense: text("今月の支出"),
  dashboardMonthBalance: text("残高"),
  dashboardRecentTitle: text("最近の記録"),
  dashboardRecentEmpty: text("まだ記録がありません"),
  assetsTitle: text("資産"),
  assetsSubtitle: text("資産ごとのノートを見よう"),
  ledgerTitleAll: text("資産（全体）"),
  ledgerSubtitleAll: text("全体をまとめて確認"),
  assetLedgerTitle: textWith(({ assetName }) => (assetName ? `資産（${assetName}）` : "資産")),
  assetLedgerSubtitle: textWith(({ balance }) => `残高 ${balance ?? ""}`.trim()),
  summaryLabel: text("サマリー"),
  summaryIncome: text("収入"),
  summaryExpense: text("支出"),
  summaryBalance: text("残高"),
  filterPresetThisMonth: text("今月"),
  filterPresetLastMonth: text("先月"),
  filterPresetLast30: text("30日間"),
  filterPresetCustom: text("その他"),
  filterSearchPlaceholder: text("検索（相手/メモ）"),
  filterOrderPlaceholder: text("並び"),
  filterOrderNew: text("新しい"),
  filterOrderOld: text("古い"),
  labelDate: text("日付"),
  labelAsset: text("資産"),
  labelCounterparty: text("相手"),
  labelCategory: text("カテゴリ"),
  labelAmount: text("金額"),
  labelBalance: text("残高"),
  labelExpense: text("支出"),
  labelIncome: text("収入"),
  labelTransferFee: text("手数料"),
  placeholderAsset: text("資産"),
  placeholderCategory: text("カテゴリ"),
  placeholderCounterparty: text("相手"),
  placeholderAmount: text("金額"),
  placeholderTransferFrom: text("移動元"),
  placeholderTransferTo: text("移動先"),
  placeholderTransferFee: text("手数料"),
  actionAdd: text("追加"),
  actionSave: text("保存"),
  actionDelete: text("削除"),
  actionReorder: text("並び替え"),
  toastAmountRequired: text("金額を入力してね"),
  toastAssetRequired: text("資産を選んでね"),
  toastCategoryRequired: text("カテゴリを選んでね"),
  toastTransferAssetRequired: text("移動先の資産を選んでね"),
  toastTransferSameAsset: text("同じ資産には移動できないよ"),
  toastEntryAdded: text("記録を追加したよ"),
  toastEntryUpdated: text("記録を更新したよ"),
  toastEntryDeleted: text("記録を削除したよ"),
  confirmDeleteEntry: text("この記録を削除する？"),
  dialogEditEntryTitle: text("記録を更新"),
  unknownError: text("不明なエラー"),
  transferToOption: textWith(({ assetName }) => (assetName ? `→${assetName} へ` : "→")),
  transferFromOption: textWith(({ assetName }) => (assetName ? `←${assetName} から` : "←")),
  personalSettingsGradeDescription: text("学年に合わせて表記が変わるよ"),
  personalSettingsGradeNote: text("4月1日以後に初回アクセスすると1学年進むよ"),
  assetsSettingsTitle: text("資産設定"),
  assetsSettingsSubtitle: text("資産を追加・編集する"),
  assetsSettingsNewTitle: text("新しい資産"),
  assetsSettingsEmpty: text("資産がまだありません"),
  assetsSettingsName: text("名前"),
  assetsSettingsType: text("種類"),
  assetsSettingsInitialBalance: text("初期残高"),
  assetsSettingsInitialBalanceAlt: text("初期残高"),
  assetsSettingsCurrentBalance: text("現在残高"),
  assetsSettingsNoType: text("（種類なし）"),
  assetsSettingsNoMemo: text("（メモなし）"),
  assetsSettingsActive: text("有効"),
  assetsSettingsAdd: text("追加"),
  assetsSettingsSaveAria: text("保存"),
  assetsSettingsDeleteAria: textWith(({ name }) => `${name ?? ""} を削除`.trim()),
  toastNameRequired: text("名前を入力してね"),
  toastInitialBalanceRequired: text("残高を入力してね"),
  toastAssetAdded: text("資産を追加したよ"),
  toastAssetUpdated: text("資産を更新したよ"),
  toastAssetDeleted: text("資産を削除したよ"),
  confirmDeleteAsset: text("この資産を削除する？"),
  categoriesSettingsTitle: text("カテゴリ設定"),
  categoriesSettingsSubtitle: text("カテゴリを追加・編集する"),
  categoriesSettingsNewTitle: text("新しいカテゴリ"),
  categoriesSettingsExpense: text("支出"),
  categoriesSettingsIncome: text("収入"),
  categoriesSettingsAdd: text("追加"),
  toastCategoryAdded: text("カテゴリを追加したよ"),
  toastCategoryUpdated: text("カテゴリを更新したよ"),
  toastCategoryDeleted: text("カテゴリを削除したよ"),
  confirmDeleteCategory: text("このカテゴリを削除する？"),
  toastOtherNotAllowed: text("「その他」は使えません"),
  confirmCategoryMerge: text("同じ名前があります。まとめていい？"),
  dataExportDescription1: text("すべての取引データをダウンロードします。"),
  dataExportDescription2: text("バックアップや表計算ソフトでの利用に使えます。"),
});
